# Generated by Django 4.1.7 on 2023-04-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_created_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cpf",
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
