# Generated by Django 4.1.7 on 2023-04-06 23:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="team",
            field=models.CharField(default="", max_length=200, verbose_name="Equipe"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workplace",
            name="address",
            field=models.CharField(max_length=200, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="hour_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Preço por hora",
            ),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Localização"),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome do local"),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Trabalhador",
            ),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="turn_size_hours",
            field=models.IntegerField(verbose_name="Horas diárias"),
        ),
    ]
