# Generated by Django 4.1.7 on 2023-04-06 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workplaces",
            old_name="turn_hours",
            new_name="turn_size_hours",
        ),
    ]
