# Generated by Django 4.1.7 on 2023-04-06 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workplaces", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "begin",
                    models.DateTimeField(auto_now_add=True, verbose_name="Início"),
                ),
                (
                    "end",
                    models.DateTimeField(default=None, null=True, verbose_name="Fim"),
                ),
                (
                    "begin_position",
                    models.CharField(max_length=200, verbose_name="Posição no início"),
                ),
                (
                    "end_position",
                    models.CharField(max_length=200, verbose_name="Posição no fim"),
                ),
                (
                    "begin_photo",
                    models.ImageField(
                        upload_to="shift_photos/", verbose_name="Foto de entrada"
                    ),
                ),
                (
                    "end_photo",
                    models.ImageField(
                        upload_to="shift_photos/", verbose_name="Foto de saída"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, verbose_name="Ponto está em aberto?"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dono",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workplaces.workplace",
                        verbose_name="Local de trabalho",
                    ),
                ),
            ],
        ),
    ]
