# Generated by Django 4.1.7 on 2023-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="begin_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/shift_photos",
                verbose_name="Foto de entrada",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="end",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fim"
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="end_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/shift_photos",
                verbose_name="Foto de saída",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="end_position",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Posição no fim"
            ),
        ),
    ]
