# Generated by Django 4.1.7 on 2023-04-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_name_profile_full_name"),
        ("shifts", "0002_alter_shift_begin_photo_alter_shift_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="owner",
        ),
        migrations.AddField(
            model_name="shift",
            name="owner_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profile",
                verbose_name="Perfil do usuário",
            ),
        ),
    ]
